### ISSUE TITLE
[db] Use fully qualified import paths in UserValue macro

### ISSUE THREAD

**Issue by teodosin** [agnesoft/agdb#1051]
The UserValue macro breaks if you have a different Result imported in the same file. Having `use std::fmt::Result;` in a file produced the error `type alias takes 0 generic arguments but 2 generic arguments were supplied` on the macro call. This seems to be because the macro uses a different Result type implicitly. It seems to me like care has been taken to avoid this with the other types that are used in the macro, but this one has been missed.

**Comment by michaelvlach** [comment]
Good catch, will fix it asap.

**Comment by michaelvlach** [comment]
@teodosin This should now be fixed in 0.6.7: https://github.com/agnesoft/agdb/releases/tag/v0.6.7
