### ISSUE TITLE
[server] Db objects are not recreated upon server restart

### ISSUE THREAD

**Issue by pinghe** [agnesoft/agdb#1093]
I attempted the following sequence:

1. user_login_admin
2. admin_user_add
3. user_logout
4. User_login
5. db_add
6. user_logout
7. user_login_admin
8. admin_shutdown

Then, upon restarting the agdb_server:
a. user_login
b. db_list --- error, indicating the database was not found.

However, if after the db_add step in the initialization process, I add:
5.1. db_backup

And after restarting the agdb_server, I then add:
a.1. db_restore
after the user_login step, everything works normally.

Is this a requirement, or is it a malfunction?

**Comment by michaelvlach** [comment]
It is a genuine issue. The dbs are stored in the internal database but the db objects are not being recreated upon restart of the server. The backup/restore works because it does create new db object. Let me fix it.

**Comment by michaelvlach** [comment]
This is now fixed and released in version 0.6.9
