### ISSUE TITLE
[server] Database Location Change After agdb_server Restart Causes Data Inaccessibility

### ISSUE THREAD

**Issue by pinghe** [agnesoft/agdb#1133]
I have encountered an issue with the user database that affects data accessibility after the database process restarts. Here's a detailed description of the steps and the issue:

## Command Sequence Execution:
![image](https://github.com/agnesoft/agdb/assets/377955/9f4db7ae-8af9-4989-b500-f746f30848c3)

````
user_login_admin
admin_user_add // Creates a user named user1
user_logout
user_login // user1 logs in
db_add // Creates a database named user1db
````
![image](https://github.com/agnesoft/agdb/assets/377955/17852ceb-f47c-4a34-8006-de61c7779cde)

## Directory Check:

Upon checking the directory, user1db is located within the user1 directory. This is as expected.
![image](https://github.com/agnesoft/agdb/assets/377955/c09a9d08-bbe2-47d8-a3d7-caa51b74f3bc)
![image](https://github.com/agnesoft/agdb/assets/377955/23c385bf-c86a-4dc9-8d70-44d1544675fc)
![image](https://github.com/agnesoft/agdb/assets/377955/6ccde670-a260-4ea9-bdbc-4cbbba605b45)

## agdb_server Restart:

After restarting the agdb_server, it is observed that a new user1db is created within the agdb_server_data directory, and the database in the user1 directory is not used.
![image](https://github.com/agnesoft/agdb/assets/377955/9c50b08c-9ae0-46d8-81b2-74755a448be6)

## Expected Behavior:

The user1db database should retain its location within the user1 directory after the agdb_server restarts.

## Actual Behavior:

The agdb_server creates a new instance of user1db in the agdb_server_data directory upon restart, which leads to data inaccessibility.

## Steps to Reproduce:

Follow the command sequence as listed above.
Verify the location of user1db.
Restart the agdb_server and observe the behavior.

## Additional Information:

This issue impacts the reliability of the database system as data becomes inaccessible post-restart.
I have not made any changes to the default configuration settings.

Could you please look into this and advise on the necessary steps to resolve this issue?

Thank you for your attention to this matter.

Best regards,
pinghe

**Comment by michaelvlach** [comment]
@pinghe Thanks for reporting. This is now fixed. The issue this time was a typo in the variable name used for reloading the databases after restart. As always I have put in tests to guard against such issues in the future. Cheers.
