### ISSUE TITLE
[db] bug Alias Update Issue with Value Overwriting Instead of Appending

### ISSUE THREAD

**Issue by pinghe** [agnesoft/agdb#1136]
I've encountered an issue with the current implementation of the alias handling in our system. The behavior is not consistent with the expected outcome when updating or creating values for existing aliases.

### Description of the Expected Behavior:

1. If the alias does not exist, a new one should be created and values should be set accordingly.
2. If the alias already exists, a new value should be appended or an existing one should be updated, without duplication.

### Current Behavior:

The system successfully creates a new alias when it doesn't exist and sets the values.
However, when an alias exists, the system does not update the existing value but instead creates a new one, leading to repeated insertions of the same value (order in this case).

### Input
````
{
    "ids": {
        "Ids": []
    },
    "aliases": [
        "node1"
    ],
    "count": 0,
    "values": {
        "Multi": [
            [
                {
                    "key": {
                        "String": "order"
                    },
                    "value": {
                        "U64": 3
                    }
                }
            ]
        ]
    }
}
````
### Steps to Reproduce:

Execute the provided imput through the system.
Observe the behavior of the system with respect to alias and value handling.

This issue affects the integrity of our data as it leads to unnecessary duplication of values.
I have verified that the issue is consistent across different test cases.
Could you please look into this and provide an update on how to resolve it?

Thank you for your attention to this matter.

Best regards,
pinghe

**Comment by michaelvlach** [comment]
@pinghe I know you have closed this but I have tested it anyway and could not reproduce the issue. Is there anything specific you were trying that was beahving as you described? I want to be sure it really isn't an issue. :-) Thanks!

**Comment by pinghe** [comment]
@michaelvlach  Hi there, no worries! It turns out the issue was on my end due to a mistake in my code. Thanks for taking the time to check it out! 😊
