### ISSUE TITLE
[server] db_user_add  405 Method Not Allowed

### ISSUE THREAD

**Issue by pinghe** [agnesoft/agdb#1183]
/api/v1/db/{owner}/{db}/user/{username}/add

< 405 Method Not Allowed
< allow: PUT
< content-length: 0

**Comment by michaelvlach** [comment]
@pinghe This should now be fixed. The change was done to the openapi so the apis have changed. Note that I have not yet released the latest fixes to it so you would need to take the code from here. Or if you would prefer it asap I can release it sooner. I plan to release 0.8.0 once the PHP api is finished (should be few days I reckon). Let me know, I can do a bugfix release if you would appreciate it!

**Comment by pinghe** [comment]
@michaelvlach Thanks for the update! Since you're planning to release version 0.8.0 once the PHP API is completed, I'm happy to wait for that release.

I appreciate your offer to do a bugfix release sooner if needed, but I think it's fine to proceed with the scheduled release plan. Please go ahead with your current timeline, and I'll update my code once the new version is available.

Looking forward to the release and thanks again for your prompt attention to this issue.

**Comment by agnesoft** [comment]
@pinghe 0.8.0 is now out! You can update the agdb_api package to that version and get all the fixes.
