### ISSUE TITLE
Thanks for agdb!

### ISSUE THREAD

**Issue by nerdachse** [agnesoft/agdb#745]
Dear creator!

I wanted to say thank you very much for this awesome project.

This and bonsaidb are extremely interesting to me, and I am currently evaluating it for a project of mine.
I love the design, the philosophy and hopefully also the performance :D 

Thanks for sharing this!

**Comment by michaelvlach** [comment]
Thank you. :-) Please let me know if you encounter any issues or things that are unclear or could be improved. I am using it myself but more people would mean more input of course.

As for the performance try running the `agdb_benchmarks` and see if you like the results or just skim through my [analysis](https://github.com/agnesoft/agdb/blob/main/docs/performance.md).

Cheers!
