### ISSUE TITLE
[studio] Add project

### ISSUE THREAD

**Issue by michaelvlach** [agnesoft/agdb#755]
Add project named `agdb_studio` with initial code for the frontend application.

**Comment by michaelvlach** [comment]
![Image](https://github.com/agnesoft/agdb/assets/11575751/cf9c4d1c-d312-4b6f-b406-100709e72477)

**Comment by janavlachova** [comment]
![Image](https://github.com/agnesoft/agdb/assets/65499282/562cdcf1-c412-4d36-be62-d2b4db9a5269)

**Comment by janavlachova** [comment]
![Image](https://github.com/agnesoft/agdb/assets/65499282/6c005fe5-7b96-49a5-8952-b1a8bca59eaa)

**Comment by janavlachova** [comment]
![logo5 - kopie](https://github.com/agnesoft/agdb/assets/65499282/5a76d3e5-03b0-4aa7-ac4f-27e1dba35311)
